import type { ComponentType, SVGProps } from 'react'
import { icons } from 'lucide-react'
import * as PhosphorIcons from '@phosphor-icons/react'

export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>

const PHOSPHOR_SKIP = new Set(['IconBase', 'IconContext', 'SSR', 'default'])

function pascalToKebab(str: string): string {
	return str
		.replace(/([a-z])([A-Z])/g, '$1-$2')
		.replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
		.replace(/([a-zA-Z])(\d)/g, '$1-$2')
		.replace(/(\d)([a-zA-Z])/g, '$1-$2')
		.toLowerCase()
}

// ── Lucide icons (~1671) ────────────────────────────────────────────────
const LUCIDE_ICON_MAP: Record<string, IconComponent> = {}
for (const [pascalName, icon] of Object.entries(icons)) {
	LUCIDE_ICON_MAP[pascalToKebab(pascalName)] = icon as IconComponent
}
LUCIDE_ICON_MAP['gamepad'] = LUCIDE_ICON_MAP['gamepad-2']

// ── Phosphor icons (~1512) ──────────────────────────────────────────────
const PHOSPHOR_ICON_MAP: Record<string, IconComponent> = {}
for (const [name, icon] of Object.entries(PhosphorIcons)) {
	if (PHOSPHOR_SKIP.has(name) || name.endsWith('Icon')) continue
	PHOSPHOR_ICON_MAP[pascalToKebab(name)] = icon as IconComponent
}

// ── Combined map (lucide plain, phosphor prefixed) for search ───────────
export const ALL_ICON_MAP: Record<string, IconComponent> = {}
for (const [name, icon] of Object.entries(LUCIDE_ICON_MAP)) {
	ALL_ICON_MAP[name] = icon
}
for (const [name, icon] of Object.entries(PHOSPHOR_ICON_MAP)) {
	ALL_ICON_MAP[`phosphor:${name}`] = icon
}

// ── Resolve any icon name ───────────────────────────────────────────────
export function getFolderIcon(name: string | null | undefined): IconComponent {
	if (!name) return icons.Folder as IconComponent
	if (name.startsWith('phosphor:')) {
		const phosphorName = name.slice(9)
		return PHOSPHOR_ICON_MAP[phosphorName] ?? (icons.Folder as IconComponent)
	}
	return LUCIDE_ICON_MAP[name] ?? (icons.Folder as IconComponent)
}

// ── Merged categories (Lucide + Phosphor side by side) ──────────────────
// Phosphor icons are prefixed with 'phosphor:' for DB storage
export const ICON_CATEGORIES: { label: string; icons: string[] }[] = [
	{
		label: 'General',
		icons: [
			'folder',
			'star',
			'heart',
			'bookmark',
			'flag',
			'tag',
			'target',
			'circle-dot',
			'flame',
			'zap',
			'lightbulb',
			'sun',
			'moon',
			'sparkles',
			'thumbs-up',
			'crown',
			'gem',
			'award',
			'rainbow',
			'infinity',
			'eye',
			'bell',
			'phosphor:folder',
			'phosphor:star',
			'phosphor:heart',
			'phosphor:bookmark-simple',
			'phosphor:flag',
			'phosphor:tag',
			'phosphor:target',
			'phosphor:fire',
			'phosphor:lightning',
			'phosphor:lightbulb',
			'phosphor:sun',
			'phosphor:moon',
			'phosphor:sparkle',
			'phosphor:thumbs-up',
			'phosphor:crown',
			'phosphor:diamond',
			'phosphor:trophy',
			'phosphor:medal',
			'phosphor:eye',
			'phosphor:bell',
			'phosphor:push-pin',
			'phosphor:shooting-star',
		],
	},
	{
		label: 'Travail',
		icons: [
			'briefcase',
			'building',
			'clipboard',
			'chart-bar',
			'calendar',
			'clock',
			'mail',
			'inbox',
			'list-todo',
			'pen-tool',
			'chart-line',
			'chart-pie',
			'presentation',
			'kanban',
			'notebook',
			'timer',
			'stamp',
			'list-checks',
			'calculator',
			'phosphor:briefcase',
			'phosphor:building-office',
			'phosphor:clipboard',
			'phosphor:chart-bar',
			'phosphor:calendar',
			'phosphor:clock',
			'phosphor:envelope',
			'phosphor:tray',
			'phosphor:list-checks',
			'phosphor:pen',
			'phosphor:chart-line',
			'phosphor:chart-pie',
			'phosphor:presentation',
			'phosphor:kanban',
			'phosphor:notebook',
			'phosphor:timer',
			'phosphor:stamp',
			'phosphor:calculator',
			'phosphor:strategy',
			'phosphor:chart-donut',
		],
	},
	{
		label: 'Tech',
		icons: [
			'code',
			'terminal',
			'cpu',
			'database',
			'server',
			'cloud',
			'globe',
			'laptop',
			'monitor',
			'smartphone',
			'bug',
			'rocket',
			'git-branch',
			'git-merge',
			'wifi',
			'hard-drive',
			'circuit-board',
			'binary',
			'code-xml',
			'blocks',
			'bot',
			'brain-circuit',
			'container',
			'webhook',
			'phosphor:code',
			'phosphor:terminal',
			'phosphor:cpu',
			'phosphor:database',
			'phosphor:hard-drives',
			'phosphor:cloud',
			'phosphor:globe',
			'phosphor:laptop',
			'phosphor:monitor',
			'phosphor:device-mobile',
			'phosphor:bug',
			'phosphor:rocket',
			'phosphor:git-branch',
			'phosphor:git-merge',
			'phosphor:wifi-high',
			'phosphor:hard-drive',
			'phosphor:circuitry',
			'phosphor:binary',
			'phosphor:code-block',
			'phosphor:robot',
			'phosphor:head-circuit',
			'phosphor:webhooks-logo',
			'phosphor:brain',
			'phosphor:atom',
		],
	},
	{
		label: 'Media',
		icons: [
			'image',
			'camera',
			'video',
			'film',
			'music',
			'mic',
			'tv',
			'newspaper',
			'palette',
			'brush',
			'pen',
			'pencil',
			'headphones',
			'radio',
			'aperture',
			'clapperboard',
			'drama',
			'phosphor:image',
			'phosphor:camera',
			'phosphor:video-camera',
			'phosphor:film-strip',
			'phosphor:music-note',
			'phosphor:microphone',
			'phosphor:television',
			'phosphor:newspaper',
			'phosphor:palette',
			'phosphor:paint-brush',
			'phosphor:pen-nib',
			'phosphor:pencil',
			'phosphor:headphones',
			'phosphor:radio',
			'phosphor:aperture',
			'phosphor:film-slate',
			'phosphor:vinyl-record',
			'phosphor:guitar',
			'phosphor:piano-keys',
			'phosphor:speaker-high',
		],
	},
	{
		label: 'Education',
		icons: [
			'book',
			'book-open',
			'graduation-cap',
			'school',
			'brain',
			'search',
			'file-text',
			'library',
			'notebook-pen',
			'atom',
			'microscope',
			'telescope',
			'flask-conical',
			'university',
			'test-tube',
			'beaker',
			'phosphor:book',
			'phosphor:book-open',
			'phosphor:graduation-cap',
			'phosphor:student',
			'phosphor:brain',
			'phosphor:magnifying-glass',
			'phosphor:file-text',
			'phosphor:books',
			'phosphor:notebook',
			'phosphor:atom',
			'phosphor:microscope',
			'phosphor:telescope',
			'phosphor:flask',
			'phosphor:university',
			'phosphor:test-tube',
			'phosphor:dna',
			'phosphor:exam',
			'phosphor:chalkboard',
			'phosphor:lectern',
		],
	},
	{
		label: 'Finance',
		icons: [
			'wallet',
			'banknote',
			'credit-card',
			'shopping-cart',
			'shopping-bag',
			'gift',
			'package',
			'store',
			'receipt',
			'coins',
			'piggy-bank',
			'badge-dollar-sign',
			'percent',
			'barcode',
			'shopping-basket',
			'hand-coins',
			'phosphor:wallet',
			'phosphor:money',
			'phosphor:credit-card',
			'phosphor:shopping-cart',
			'phosphor:shopping-bag',
			'phosphor:gift',
			'phosphor:package',
			'phosphor:storefront',
			'phosphor:receipt',
			'phosphor:coins',
			'phosphor:piggy-bank',
			'phosphor:currency-dollar',
			'phosphor:percent',
			'phosphor:barcode',
			'phosphor:shopping-bag-open',
			'phosphor:hand-coins',
			'phosphor:bank',
			'phosphor:cash-register',
			'phosphor:invoice',
		],
	},
	{
		label: 'Communication',
		icons: [
			'message-circle',
			'message-square',
			'phone',
			'send',
			'at-sign',
			'megaphone',
			'podcast',
			'radio-tower',
			'speech',
			'voicemail',
			'rss',
			'satellite-dish',
			'phosphor:chat-circle',
			'phosphor:chat',
			'phosphor:phone',
			'phosphor:paper-plane-tilt',
			'phosphor:at',
			'phosphor:megaphone',
			'phosphor:podcast',
			'phosphor:cell-tower',
			'phosphor:voicemail',
			'phosphor:rss',
			'phosphor:satellite-dish',
			'phosphor:envelope',
			'phosphor:chat-dots',
			'phosphor:chats',
			'phosphor:broadcast',
			'phosphor:translate',
		],
	},
	{
		label: 'Personnes',
		icons: [
			'user',
			'users',
			'baby',
			'person-standing',
			'circle-user',
			'user-plus',
			'user-round',
			'contact',
			'accessibility',
			'hand',
			'hand-heart',
			'heart-handshake',
			'phosphor:user',
			'phosphor:users',
			'phosphor:baby',
			'phosphor:person',
			'phosphor:user-circle',
			'phosphor:user-plus',
			'phosphor:user-list',
			'phosphor:identification-card',
			'phosphor:hand',
			'phosphor:hand-heart',
			'phosphor:handshake',
			'phosphor:person-simple-walk',
			'phosphor:person-simple-run',
			'phosphor:person-arms-spread',
			'phosphor:detective',
		],
	},
	{
		label: 'Nature & Animaux',
		icons: [
			'tree-pine',
			'tree-deciduous',
			'flower',
			'flower-2',
			'leaf',
			'mountain',
			'bird',
			'fish',
			'paw-print',
			'sprout',
			'trees',
			'cat',
			'dog',
			'rabbit',
			'snail',
			'turtle',
			'clover',
			'shrub',
			'wheat',
			'squirrel',
			'phosphor:tree',
			'phosphor:tree-evergreen',
			'phosphor:flower',
			'phosphor:flower-lotus',
			'phosphor:leaf',
			'phosphor:mountains',
			'phosphor:bird',
			'phosphor:fish',
			'phosphor:paw-print',
			'phosphor:plant',
			'phosphor:potted-plant',
			'phosphor:cat',
			'phosphor:dog',
			'phosphor:rabbit',
			'phosphor:butterfly',
			'phosphor:horse',
			'phosphor:flower-tulip',
			'phosphor:cactus',
			'phosphor:tree-palm',
			'phosphor:acorn',
		],
	},
	{
		label: 'Transport',
		icons: [
			'car',
			'plane',
			'bus',
			'bike',
			'truck',
			'train-front',
			'ship',
			'fuel',
			'map-pin',
			'navigation',
			'compass',
			'sailboat',
			'motorbike',
			'helicopter',
			'ambulance',
			'cable-car',
			'scooter',
			'phosphor:car',
			'phosphor:airplane',
			'phosphor:bus',
			'phosphor:bicycle',
			'phosphor:truck',
			'phosphor:train',
			'phosphor:boat',
			'phosphor:gas-pump',
			'phosphor:map-pin',
			'phosphor:navigation-arrow',
			'phosphor:compass',
			'phosphor:sailboat',
			'phosphor:motorcycle',
			'phosphor:helicopter',
			'phosphor:ambulance',
			'phosphor:cable-car',
			'phosphor:scooter',
			'phosphor:taxi',
			'phosphor:jeep',
			'phosphor:tram',
		],
	},
	{
		label: 'Nourriture',
		icons: [
			'apple',
			'pizza',
			'cake',
			'cherry',
			'croissant',
			'egg',
			'grape',
			'banana',
			'carrot',
			'popcorn',
			'sandwich',
			'soup',
			'cookie',
			'ice-cream-cone',
			'milk',
			'wine',
			'beer',
			'ham',
			'beef',
			'salad',
			'cake-slice',
			'dessert',
			'phosphor:orange-slice',
			'phosphor:pizza',
			'phosphor:cake',
			'phosphor:cherries',
			'phosphor:croissant',
			'phosphor:egg',
			'phosphor:orange',
			'phosphor:avocado',
			'phosphor:carrot',
			'phosphor:popcorn',
			'phosphor:hamburger',
			'phosphor:bowl-food',
			'phosphor:cookie',
			'phosphor:ice-cream',
			'phosphor:coffee',
			'phosphor:wine',
			'phosphor:beer-stein',
			'phosphor:shrimp',
			'phosphor:bowl-steam',
			'phosphor:bread',
		],
	},
	{
		label: 'Sport & Loisirs',
		icons: [
			'gamepad-2',
			'trophy',
			'dumbbell',
			'medal',
			'swords',
			'dice-5',
			'puzzle',
			'tent',
			'volleyball',
			'biceps-flexed',
			'joystick',
			'kayak',
			'roller-coaster',
			'ferris-wheel',
			'party-popper',
			'guitar',
			'drum',
			'phosphor:game-controller',
			'phosphor:trophy',
			'phosphor:barbell',
			'phosphor:medal',
			'phosphor:sword',
			'phosphor:dice-five',
			'phosphor:puzzle-piece',
			'phosphor:tent',
			'phosphor:volleyball',
			'phosphor:joystick',
			'phosphor:basketball',
			'phosphor:soccer-ball',
			'phosphor:tennis-ball',
			'phosphor:baseball',
			'phosphor:football',
			'phosphor:ping-pong',
			'phosphor:racquet',
			'phosphor:swimming-pool',
			'phosphor:confetti',
		],
	},
	{
		label: 'Sante',
		icons: [
			'heart-pulse',
			'stethoscope',
			'pill',
			'syringe',
			'thermometer',
			'activity',
			'bandage',
			'hospital',
			'cross',
			'pill-bottle',
			'ear',
			'scan-heart',
			'phosphor:heartbeat',
			'phosphor:stethoscope',
			'phosphor:pill',
			'phosphor:syringe',
			'phosphor:thermometer',
			'phosphor:first-aid-kit',
			'phosphor:bandaids',
			'phosphor:hospital',
			'phosphor:dna',
			'phosphor:tooth',
			'phosphor:ear',
			'phosphor:wheelchair',
			'phosphor:face-mask',
			'phosphor:prescription',
		],
	},
	{
		label: 'Vie quotidienne',
		icons: [
			'home',
			'coffee',
			'utensils',
			'umbrella',
			'map',
			'bed',
			'lamp-desk',
			'sofa',
			'cooking-pot',
			'shirt',
			'scissors',
			'door-open',
			'armchair',
			'key',
			'washing-machine',
			'refrigerator',
			'bath',
			'shower-head',
			'phosphor:house',
			'phosphor:coffee',
			'phosphor:fork-knife',
			'phosphor:umbrella',
			'phosphor:map-trifold',
			'phosphor:bed',
			'phosphor:lamp',
			'phosphor:couch',
			'phosphor:cooking-pot',
			'phosphor:t-shirt',
			'phosphor:scissors',
			'phosphor:door-open',
			'phosphor:armchair',
			'phosphor:key',
			'phosphor:washing-machine',
			'phosphor:bathtub',
			'phosphor:shower',
			'phosphor:broom',
			'phosphor:toilet',
		],
	},
	{
		label: 'Fichiers',
		icons: [
			'file',
			'file-text',
			'file-code',
			'file-image',
			'folder-open',
			'paperclip',
			'save',
			'clipboard-list',
			'scroll',
			'file-music',
			'file-spreadsheet',
			'file-archive',
			'files',
			'folder-tree',
			'notebook-tabs',
			'phosphor:file',
			'phosphor:file-text',
			'phosphor:file-code',
			'phosphor:file-image',
			'phosphor:folder-open',
			'phosphor:paperclip',
			'phosphor:floppy-disk',
			'phosphor:clipboard-text',
			'phosphor:scroll',
			'phosphor:file-audio',
			'phosphor:file-video',
			'phosphor:file-pdf',
			'phosphor:file-zip',
			'phosphor:files',
			'phosphor:folders',
			'phosphor:tree-structure',
			'phosphor:note',
		],
	},
	{
		label: 'Systeme',
		icons: [
			'settings',
			'wrench',
			'lock',
			'shield',
			'download',
			'archive',
			'box',
			'layers',
			'link',
			'fingerprint-pattern',
			'scan',
			'shield-check',
			'cctv',
			'eye-off',
			'lock-keyhole',
			'upload',
			'scan-face',
			'phosphor:gear',
			'phosphor:wrench',
			'phosphor:lock',
			'phosphor:shield',
			'phosphor:download',
			'phosphor:archive',
			'phosphor:cube',
			'phosphor:stack',
			'phosphor:link',
			'phosphor:fingerprint',
			'phosphor:scan',
			'phosphor:shield-check',
			'phosphor:security-camera',
			'phosphor:eye-slash',
			'phosphor:lock-key',
			'phosphor:upload',
			'phosphor:plugs-connected',
			'phosphor:terminal-window',
		],
	},
]
